<a href="https://colab.research.google.com/github/Thatha-Madhavi/Machine-Learning-and-Deep-Learning-Concepts/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy :

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
a = np.array(42)
b = np.array([[1,2,3], [4,5,6]])
c = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

In [ ]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
2
3


In [ ]:
arr = np.array([1,2,3,4,34,76,21])
print(arr[3] + arr[6])

25


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd Element on 1st row:' , arr[1,3])

2nd Element on 1st row: 9


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr[1,1,2])

6
12


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim:' , arr[0,-1])

last element from 2nd dim: 5


Array Slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[2:6:2])
print(arr[0:6:3])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[3 5]
[1 4]
[1 3 5 7]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])
print(arr[0, 0:3])
print(arr[0:2,2])
print(arr[0:2,4])
print(arr[0:2,2])
print(arr[0:1,3])
print (arr[0:1,2:4])

[7 8 9]
[1 2 3]
[3 8]
[ 5 10]
[3 8]
[4]
[[3 4]]


In [ ]:
arr = np.array([1,2,3,4,5])
(arr.dtype)

dtype('int64')

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
