In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [ ]:
df = pd.read_csv('sample_data/spam.csv')

In [ ]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [ ]:
747/4825

0.15481865284974095

In [ ]:
df_spam = df[df['Category'] == 'spam']
df_ham = df[df['Category'] == 'ham']
df_ham_downsampled = df_ham.sample(df_spam.shape[0])
df_balanced = pd.concat([df_spam, df_ham_downsampled])
df_balanced['Category'].value_counts()
df_balanced['spam'] = df_balanced['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df_balanced.head()

Category                                            Message  spam
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
5      spam  FreeMsg Hey there darling it's been 3 week's n...     1
8      spam  WINNER!! As a valued network customer you have...     1
9      spam  Had your mobile 11 months or more? U R entitle...     1
11     spam  SIX chances to win CASH! From 100 to 20,000 po...     1

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df_balanced['Message'], df_balanced['spam'], stratify=df_balanced['spam'])

In [ ]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [ ]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

In [ ]:
get_sentence_embeding([
    "500$ discount. hurry up",
    "Madhu, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8435168 , -0.5132724 , -0.8884571 , ..., -0.7474884 ,
        -0.7531473 ,  0.91964483],
       [-0.8615849 , -0.5410099 , -0.9603066 , ..., -0.90677065,
        -0.7503314 ,  0.8754765 ]], dtype=float32)>

In [ ]:
e = get_sentence_embeding([
    "watermelon",
    "grapes",
    "mango",
    "jeff bezos",
    "elon musk",
    "bill gates"
]
)

In [ ]:
cosine_similarity([e[0]],[e[1]])

array([[0.7585941]], dtype=float32)

In [ ]:
cosine_similarity([e[0]],[e[4]])

array([[0.91486746]], dtype=float32)